# conda.recipe/meta.yaml

package:
  name: my-geometry-package
  version: "0.0.1"

source:
  path: ..

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools # Add this line
    - _libgcc_mutex 0.1 conda_forge
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgomp 15.1.0 h767d61c_5
    - python_abi 3.13 8_cp313
    - tzdata 2025b h78e105d_0
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_5
    - bzip2 1.0.8 hda65f42_8
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - liblzma 5.8.1 hb9d3cd8_2
    - libmpdec 4.0.0 hb9d3cd8_0
    - libuuid 2.41.2 he9a06e4_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.3 h26f9b46_1
    - libsqlite 3.50.4 h0c1763c_0
    - readline 8.2 h8c095d6_2
    - tk 8.6.13 noxft_hd72426e_102
    - python 3.13.7 h2b335a9_100_cp313
    - pip 25.2 pyh145f28c_0
  run:
    - python >=3.6

about:
  home: "https://github.com/yourusername/my-geometry-package"
  license: MIT
  summary: "A simple package to calculate geometric shapes area."
  description: "This is a simple package for calculating the area of circles and squares."

extra:
  recipe-maintainers:
    - MikeACedric