name: Conda Package Publisher

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          channels: conda-forge,defaults

      - name: Build and upload conda package
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          # Ensure we are inside the base conda environment
          source $CONDA/bin/activate base

          # Install required tools
          conda install -y conda-build anaconda-client

          # Build the package
          conda build --output-folder build .

          # Upload the built package
          anaconda upload --label main build/noarch/*.conda || anaconda upload --label main build/linux-64/*.conda